### ISSUE TITLE
Bug in model downloader

### ISSUE THREAD

**Issue by devkapilbansal** [freshlybuiltongithub/freshylbuiltimagejaano#6]
@ravi5175 Tried to use the library but found some bugs in it.
![error1](https://user-images.githubusercontent.com/42766576/88846418-3d18ed00-d203-11ea-8d9d-8a570422881e.PNG)
When tried straight from the downloader file it runs correctly.
![error2](https://user-images.githubusercontent.com/42766576/88846545-646fba00-d203-11ea-98ff-55be4894e0d8.PNG)
But then this error occurs:- 
![error3](https://user-images.githubusercontent.com/42766576/88846622-7d786b00-d203-11ea-9afb-767e1eff790d.png)
I explicitly pass the model name in the file but then:- 
![error4](https://user-images.githubusercontent.com/42766576/88846733-a993ec00-d203-11ea-8d32-1955c096bbf8.png)

**Comment by devkapilbansal** [comment]
@vishal2612200

**Comment by ravi5175** [comment]
@KapilBansal320 'placeholder' error is due to old incompatible version of tensorflow-estimater library i think
i had revised the downloader script
Thanks for the issue you raised, we are closing it now
